version: 2
project_name: airgradient-exporter
before:
  hooks:
  - go mod tidy
  - |
    cd dashboard \
      && go mod tidy \
      && go run main.go > dashboard.json
builds:
- binary: airgradient-exporter
  env:
  - CGO_ENABLED=0
  targets:
  - linux_amd64
  - linux_arm64
release:
  extra_files:
  - glob: dashboard/dashboard.json
    name_template: airgradient-dashboard.json
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
  - goos: windows
    formats:
    - zip
  files:
  - LICENSE
  - README.md
  - systemd/*
checksum:
  name_template: checksums.txt
snapshot:
  version_template: '{{ incpatch .Version }}-next'
nfpms:
- vendor: Zebradil
  homepage: https://github.com/zebradil/airgradient-exporter
  maintainer: German Lashevich <german.lashevich@gmail.com>
  description: Prometheus exporter for AirGradient air quality sensors
  license: MIT
  formats:
  - apk
  - deb
  - rpm
  contents:
  - src: systemd/airgradient-exporter.service
    dst: /usr/lib/systemd/system/airgradient-exporter.service
  - src: systemd/override.conf.example
    dst: /usr/share/doc/airgradient-exporter/override.conf.example
dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - ghcr.io/zebradil/airgradient-exporter:{{ .Tag }}-linux-amd64
  - ghcr.io/zebradil/airgradient-exporter:{{ .Major }}-linux-amd64
  - ghcr.io/zebradil/airgradient-exporter:{{ .Major }}.{{ .Minor }}-linux-amd64
  - ghcr.io/zebradil/airgradient-exporter:latest-linux-amd64
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
- goos: linux
  goarch: arm64
  image_templates:
  - ghcr.io/zebradil/airgradient-exporter:{{ .Tag }}-linux-arm64
  - ghcr.io/zebradil/airgradient-exporter:{{ .Major }}-linux-arm64
  - ghcr.io/zebradil/airgradient-exporter:{{ .Major }}.{{ .Minor }}-linux-arm64
  - ghcr.io/zebradil/airgradient-exporter:latest-linux-arm64
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64
docker_manifests:
- name_template: ghcr.io/zebradil/airgradient-exporter:{{ .Tag }}
  image_templates:
  - ghcr.io/zebradil/airgradient-exporter:{{ .Tag }}-linux-amd64
  - ghcr.io/zebradil/airgradient-exporter:{{ .Tag }}-linux-arm64
- name_template: ghcr.io/zebradil/airgradient-exporter:{{ .Major }}
  image_templates:
  - ghcr.io/zebradil/airgradient-exporter:{{ .Major }}-linux-amd64
  - ghcr.io/zebradil/airgradient-exporter:{{ .Major }}-linux-arm64
- name_template: ghcr.io/zebradil/airgradient-exporter:{{ .Major }}.{{ .Minor }}
  image_templates:
  - ghcr.io/zebradil/airgradient-exporter:{{ .Major }}.{{ .Minor }}-linux-amd64
  - ghcr.io/zebradil/airgradient-exporter:{{ .Major }}.{{ .Minor }}-linux-arm64
- name_template: ghcr.io/zebradil/airgradient-exporter:latest
  image_templates:
  - ghcr.io/zebradil/airgradient-exporter:latest-linux-amd64
  - ghcr.io/zebradil/airgradient-exporter:latest-linux-arm64
